In [1]:
import os
import requests
import pandas as pd
import json
from datetime import datetime, timedelta
import time
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import glob
import numpy as np
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.graphics.tsaplots import plot_acf
from scipy.stats import linregress
import statsmodels.api as sm

#  Basic Logistic Regression Model #

In [2]:
frame=pd.read_csv('pseudolabeleddata.csv')

In [3]:
frame.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'index', 'maxAutoCorrelation',
       'numberofTxns', 'stDevEosSent', 'numActiveDays', 'maxTxnsDay',
       'minTxnsDay', 'avgTxnsPerActiveDays', 'numTxnsWeekdays',
       'numTxnsWeekends', 'numActiveDaysWeekdays', 'numActiveWeekends',
       'numActiveHours', 'maxTxnsHour', 'minTxnsHour', 'txnsPerActiveHour',
       'numActiveHoursWeekdays', 'numActiveHoursWeekends', 'label', 'pred_y'],
      dtype='object')

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
log1 = LogisticRegression(random_state=42)

In [6]:
x=frame[['maxAutoCorrelation', 'numberofTxns','stDevEosSent', 'numActiveDays', 'maxTxnsDay',
       'minTxnsDay', 'avgTxnsPerActiveDays', 'numTxnsWeekdays',
       'numTxnsWeekends', 'numActiveDaysWeekdays', 'numActiveWeekends',
       'numActiveHours', 'maxTxnsHour', 'minTxnsHour', 'txnsPerActiveHour',
       'numActiveHoursWeekdays', 'numActiveHoursWeekends']]

In [7]:
sum(frame['minTxnsDay'])

0.0

In [8]:
y=frame[['pred_y']]

In [9]:
sum(y['pred_y'])

975.0

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)

In [12]:
log1.fit(train_x,train_y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=42, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
logreg_train_acc = log1.score(train_x,train_y)

In [14]:
print(logreg_train_acc)

0.9988479262672811


In [15]:
log1.predict(test_x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
log1.score(test_x, test_y)

1.0

# Cross-Validated Logistic Regression Model with All Features #

In [17]:
from sklearn.linear_model import LogisticRegressionCV

In [18]:
clf = LogisticRegressionCV(cv=5, random_state=0).fit(train_x, train_y)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:947: ConvergenceWarning: lbfgs failed to converge. In

In [19]:
clf.predict(test_x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
clf.score(test_x,test_y)

1.0

# Variance Inflation Factor #
Variance Inflation Factors were calculated to remove features that had VIF's of above 10

In [21]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
import pandas as pd

import numpy as np

from patsy import dmatrices

import statsmodels.api as sm


# For each X, calculate VIF and save in dataframe

vif = pd.DataFrame()

vif["VIF Factor"] = [variance_inflation_factor(x.values, i) for i in range(x.shape[1])]

vif["features"] = x.columns
vif

/opt/anaconda3/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1638: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.uncentered_tss


VIF Factor                features
0     174.590748      maxAutoCorrelation
1      83.668983            numberofTxns
2       1.462968            stDevEosSent
3   66761.321770           numActiveDays
4      55.360688              maxTxnsDay
5            NaN              minTxnsDay
6      25.136435    avgTxnsPerActiveDays
7      40.793298         numTxnsWeekdays
8       8.470619         numTxnsWeekends
9   40591.576266   numActiveDaysWeekdays
10   3761.674251       numActiveWeekends
11  25982.020697          numActiveHours
12     43.488949             maxTxnsHour
13           NaN             minTxnsHour
14     18.568397       txnsPerActiveHour
15  12002.936927  numActiveHoursWeekdays
16   1380.713154  numActiveHoursWeekends

In [80]:
x3=frame[['maxAutoCorrelation', 'avgTxnsPerActiveDays', 'numTxnsWeekdays',
       'numTxnsWeekends', 'txnsPerActiveHour']]

### Features that had VIF's < 10 ###

In [81]:
vif = pd.DataFrame()

vif["VIF Factor"] = [variance_inflation_factor(x3.values, i) for i in range(x3.shape[1])]

vif["features"] = x3.columns
vif

VIF Factor              features
0    3.512578    maxAutoCorrelation
1    8.281026  avgTxnsPerActiveDays
2    4.214960       numTxnsWeekdays
3    1.833036       numTxnsWeekends
4    6.871633     txnsPerActiveHour

# Cross-Validated Logistic Regression Model with Select Features #

In [5]:
train_x3, test_x3, train_y3, test_y3 = train_test_split(x3, y, test_size=0.2, random_state=42)

NameError: name 'train_test_split' is not defined

In [6]:
clf = LogisticRegressionCV(cv=5, random_state=0).fit(train_x3, train_y3)

NameError: name 'LogisticRegressionCV' is not defined

In [88]:
preds3 = clf.predict(test_x3)

In [89]:
clf.score(test_x3,test_y3)

1.0

In [90]:
from sklearn.metrics import confusion_matrix

In [92]:
confusion_matrix(test_y3, preds3)

array([[ 17,   0],
       [  0, 200]])

In [55]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(y, y_pred, average='macro')

In [22]:
x2=frame[['stDevEosSent', 'avgTxnsPerActiveDays',
       'numTxnsWeekends', 'txnsPerActiveHour']]

In [23]:
train_x2, test_x2, train_y2, test_y2 = train_test_split(x2, y, test_size=0.2, random_state=42)

In [24]:
clf = LogisticRegressionCV(cv=5, random_state=0).fit(train_x2, train_y2)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
clf.predict(test_x2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
clf.score(test_x2,test_y2)

1.0

In [27]:
len(test_y2)

217

In [28]:
test_y2

pred_y
749     1.0
56      1.0
937     1.0
270     1.0
208     1.0
..      ...
568     1.0
427     1.0
884     1.0
855     1.0
327     1.0

[217 rows x 1 columns]

In [29]:
test_x2

stDevEosSent  avgTxnsPerActiveDays  numTxnsWeekends  txnsPerActiveHour
749  0.000000e+00              1.032258              6.0                1.0
56   2.775558e-17              1.000000              5.0                1.0
937  0.000000e+00              1.032258              6.0                1.0
270  0.000000e+00              1.032258              6.0                1.0
208  0.000000e+00              1.032258              6.0                1.0
..            ...                   ...              ...                ...
568  0.000000e+00              1.032258              6.0                1.0
427  0.000000e+00              1.032258              6.0                1.0
884  0.000000e+00              1.032258              6.0                1.0
855  0.000000e+00              1.032258              6.0                1.0
327  0.000000e+00              1.032258              6.0                1.0

[217 rows x 4 columns]

# Decision Tree Model #

In [98]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

In [99]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)

In [100]:
clf = DecisionTreeClassifier()

In [101]:
clf = clf.fit(train_x,train_y)

In [102]:
y_pred = clf.predict(test_x)

In [104]:
print("Accuracy:",metrics.accuracy_score(test_y, y_pred))

Accuracy: 1.0
